openapi: 3.0.0
info:
  title: Search API
  version: v1

servers:
  - url: /to-be-changed/

paths:
  /to-be-changed:
    get:
      operationId: example endpoint to generate api doc
      description: example endpoint to generate api doc
      responses:
        '200':
          $ref: '#/components/schemas/searchResult'

components:
  schemas:
    searchResult:
      type: object
      properties:
        record:
          type: object
          description: Example response

